name: simple_algorithms
description: A collection of simple and common algorithms implemented in Dart.
version: 0.0.1
repository: https://github.com/da578/simple_algorithms

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0